-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.early_participant_trades (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  signal_id uuid NOT NULL,
  token_address text NOT NULL,
  experiment_id text,
  chain text NOT NULL DEFAULT 'bsc'::text,
  trades_data jsonb NOT NULL,
  inner_pair text,
  check_time integer NOT NULL,
  window_seconds integer DEFAULT 90,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT early_participant_trades_pkey PRIMARY KEY (id),
  CONSTRAINT early_participant_trades_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.strategy_signals(id)
);
CREATE TABLE public.experiment_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id text NOT NULL,
  experiment_name text,
  experiment_mode text,
  token_address text NOT NULL,
  token_symbol text,
  action text NOT NULL,
  executed boolean NOT NULL DEFAULT false,
  chain text DEFAULT 'bsc'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  summary jsonb DEFAULT '{}'::jsonb,
  details jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT experiment_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.experiment_time_series_data (
  id bigint NOT NULL DEFAULT nextval('experiment_time_series_data_id_seq'::regclass),
  experiment_id text NOT NULL,
  token_address text NOT NULL,
  token_symbol text,
  timestamp timestamp with time zone NOT NULL,
  loop_count integer,
  price_usd numeric,
  price_native numeric,
  factor_values jsonb,
  blockchain text DEFAULT 'bsc'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT experiment_time_series_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.experiment_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  experiment_id uuid NOT NULL,
  token_address text NOT NULL,
  token_symbol text,
  blockchain text NOT NULL,
  discovered_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'monitoring'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  raw_api_data jsonb,
  contract_security_raw_data jsonb,
  creator_address text,
  current_price_usd numeric,
  price_updated_at timestamp with time zone,
  platform character varying DEFAULT 'fourmeme'::character varying,
  analysis_results jsonb,
  human_judges jsonb,
  narrative_material_id text,
  data_source text DEFAULT 'ave_api'::text,
  CONSTRAINT experiment_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT experiment_tokens_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.experiments(id)
);
CREATE TABLE public.experiments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_name character varying NOT NULL,
  experiment_description text,
  status character varying NOT NULL DEFAULT 'initializing'::character varying,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  trading_mode character varying NOT NULL CHECK (trading_mode::text = ANY (ARRAY['virtual'::character varying, 'live'::character varying, 'backtest'::character varying]::text[])),
  strategy_type character varying NOT NULL DEFAULT 'fourmeme_earlyreturn'::character varying,
  blockchain character varying NOT NULL DEFAULT 'bsc'::character varying,
  kline_type character varying NOT NULL DEFAULT '1m'::character varying,
  started_at timestamp with time zone,
  stopped_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stats jsonb,
  CONSTRAINT experiments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.external_resource_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  url text NOT NULL,
  resource_type text NOT NULL,
  content jsonb,
  status text DEFAULT 'pending'::text,
  error_message text,
  metadata jsonb,
  cached_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT external_resource_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.narrative_analysis_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token_address text NOT NULL UNIQUE,
  token_symbol text,
  triggered_by_experiment_id text,
  status text NOT NULL DEFAULT 'pending'::text,
  priority integer DEFAULT 50,
  current_stage integer DEFAULT 0,
  narrative_id uuid,
  error_message text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT narrative_analysis_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT narrative_analysis_tasks_narrative_id_fkey FOREIGN KEY (narrative_id) REFERENCES public.token_narrative(id)
);
CREATE TABLE public.portfolio_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL,
  snapshot_time timestamp with time zone NOT NULL,
  total_value numeric DEFAULT 0,
  total_value_change numeric DEFAULT 0,
  total_value_change_percent numeric DEFAULT 0,
  cash_balance numeric DEFAULT 0,
  cash_native_balance numeric DEFAULT 0,
  total_portfolio_value_native numeric DEFAULT 0,
  token_positions jsonb DEFAULT '[]'::jsonb,
  positions_count integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT portfolio_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT fk_experiment_portfolio_snapshots FOREIGN KEY (experiment_id) REFERENCES public.experiments(id)
);
CREATE TABLE public.strategy_signals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL,
  token_address character varying NOT NULL,
  token_symbol character varying,
  chain character varying,
  signal_type character varying NOT NULL CHECK (signal_type::text = ANY (ARRAY['BUY'::character varying, 'SELL'::character varying]::text[])),
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['buy'::character varying, 'sell'::character varying, 'hold'::character varying]::text[])),
  confidence numeric,
  reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  executed boolean,
  twitter_search_duration bigint,
  twitter_search_result jsonb,
  gmgn_security_raw_data jsonb,
  gmgn_token_info_raw_data jsonb,
  CONSTRAINT strategy_signals_pkey PRIMARY KEY (id),
  CONSTRAINT fk_experiment_signals FOREIGN KEY (experiment_id) REFERENCES public.experiments(id)
);
CREATE TABLE public.token_holders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  token_address text NOT NULL,
  experiment_id text,
  holder_data jsonb NOT NULL,
  checked_at timestamp without time zone DEFAULT now(),
  snapshot_id text,
  created_at timestamp without time zone DEFAULT now(),
  signal_id uuid,
  CONSTRAINT token_holders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.token_narrative (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  token_address text NOT NULL UNIQUE,
  token_symbol text,
  platform text,
  blockchain text,
  raw_api_data jsonb,
  extracted_info jsonb,
  twitter_info jsonb,
  prompt_version text DEFAULT 'V9.0'::text,
  is_valid boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  analyzed_at timestamp with time zone,
  experiment_id text,
  prompt_type text,
  analysis_stage integer,
  classified_urls jsonb,
  pre_check_result jsonb,
  data_fetch_results jsonb,
  url_extraction_result jsonb,
  task_id uuid,
  prestage_result jsonb,
  prestage_prompt text,
  prestage_raw_output text,
  stage1_result jsonb,
  stage1_prompt text,
  stage1_raw_output text,
  stage2_result jsonb,
  stage2_prompt text,
  stage2_raw_output text,
  stage3_result jsonb,
  stage3_prompt text,
  stage3_raw_output text,
  stage_final_result jsonb,
  CONSTRAINT token_narrative_pkey PRIMARY KEY (id),
  CONSTRAINT token_narrative_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.narrative_analysis_tasks(id)
);
CREATE TABLE public.trades (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL,
  token_symbol character varying NOT NULL,
  token_address character varying NOT NULL,
  token_id character varying,
  trade_direction character varying NOT NULL CHECK (trade_direction::text = ANY (ARRAY['buy'::character varying, 'sell'::character varying]::text[])),
  trade_status character varying DEFAULT 'pending'::character varying,
  input_currency character varying NOT NULL,
  output_currency character varying NOT NULL,
  input_amount numeric NOT NULL,
  output_amount numeric,
  unit_price numeric,
  success boolean DEFAULT false,
  is_virtual_trade boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  executed_at timestamp with time zone,
  signal_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  chain text NOT NULL DEFAULT 'bsc'::text,
  CONSTRAINT trades_pkey PRIMARY KEY (id),
  CONSTRAINT trades_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.experiments(id),
  CONSTRAINT trades_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES public.strategy_signals(id)
);
CREATE TABLE public.wallets (
  id integer NOT NULL DEFAULT nextval('wallets_id_seq'::regclass),
  address text NOT NULL,
  name text,
  category character varying,
  chain text NOT NULL DEFAULT 'bsc'::text,
  tags ARRAY DEFAULT '{}'::text[],
  nickname character varying,
  twitter character varying,
  winrate numeric,
  realized_profit numeric,
  buy_count integer,
  sell_count integer,
  token_count integer,
  wallet_created_at timestamp with time zone,
  avg_holding_period integer,
  details jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wallets_pkey PRIMARY KEY (id)
);